### ISSUE TITLE
claim state at top of page

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/Claim-for-Crown-Court-Defence#1074]
this looks like it needs changing ("show" page for a claim)
<img width="1019" alt="screen shot 2016-02-24 at 11 57 16" src="https://cloud.githubusercontent.com/assets/7016425/13284747/378da2ba-daee-11e5-89ef-d1c2ecd1db17.png">

**Comment by aliuk2012** [comment]
Fixed as part of pr #1077
