### ISSUE TITLE
[FE] external user archive page column headers - wrapping issue

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/Claim-for-Crown-Court-Defence#1113]
<img width="1070" alt="screen shot 2016-03-02 at 11 02 07" src="https://cloud.githubusercontent.com/assets/7016425/13458651/6aff0738-e066-11e5-9ab9-bdcc5aeef9dd.png">

**Comment by Demwunz** [comment]
this is because of the extra column. we can address this later when we integrate tablet view
