### ISSUE TITLE
[FE] other labels too far above field - advocate category, "case cracked in", rep order date

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/Claim-for-Crown-Court-Defence#1115]
**advocate category**
<img width="713" alt="screen shot 2016-03-02 at 11 34 33" src="https://cloud.githubusercontent.com/assets/7016425/13459348/cd0789ba-e06a-11e5-8072-9c5a1db91ac4.png">

**case cracked in**
<img width="671" alt="screen shot 2016-03-02 at 11 30 31" src="https://cloud.githubusercontent.com/assets/7016425/13459260/589915da-e06a-11e5-8d3d-65af8bb28d0a.png">

**repo order date**
<img width="501" alt="screen shot 2016-03-02 at 11 32 20" src="https://cloud.githubusercontent.com/assets/7016425/13459290/77adf7e2-e06a-11e5-8d43-72c646ff7041.png">

**Comment by Demwunz** [comment]
![ministry_of_justice](https://cloud.githubusercontent.com/assets/54713/13466760/478b0388-e093-11e5-884c-d9294e33c482.jpg)

There's so many crazy things happening here to cause this...
