### ISSUE TITLE
New expense partial for claims page

### ISSUE THREAD

**Issue by Demwunz** [ministryofjustice/Claim-for-Crown-Court-Defence#1198]
[Pivotal 116030049](https://www.pivotaltracker.com/story/show/116030049)

> Implement new partial for expenses that takes into account the new schema for Expenses.  This will enable all the existing "v1" expenses / expense types to be migrated to "v2"

**Comment by Demwunz** [comment]
![expenses](https://cloud.githubusercontent.com/assets/54713/13921625/b2a00ae2-ef70-11e5-82b3-52b335700e9f.png)

**Comment by stephenrichards** [comment]
@Demwunz 
To populate the expense types dropdown, call `ExpenseType.agfs` or `ExpenseType.lgfs` depending on the claim type.

To populate the expense reasons, `call expense_type.expense_reasons_hash` = returns a hash of expense reasons keyed by id, which should be stored in expense.reason_id

If expense reason "Other" is selected (always id 5), the the free text should be stored in expense.displayable_reason_text

To display the mileage rate buttons, call `Expense::MILEAGE_RATES` - returns 

```
{
    1 => "25p per mile",
    2 => "45p per mile",
  }
```

The id of the selected rate should be stored in `expense.mileage_rate_id`

**Comment by Demwunz** [comment]
@zheileman As discussed yesterday, I think this would work well for each option:

```
<select>
<option value="foo" data-fields="{destination: false, location: true, distance: true, mileage: false, hours: false }">bar</option>
</select>
```

**Comment by zheileman** [comment]
We decided to go with the following format for the data-fields, being individual fields instead of just one:

``` html
<option data-destination="true" data-location="false" data-distance="true" data-mileage="true" data-hours="false" data-reason-set="A" value="9">Car travel</option>
```

`data-reason-set` can be 'A' or 'B' and will be matched against a javascript object containing the two different sets, each with a collection of reasons in the following format:

``` javascript
{"id":1,"reason":"Court hearing","reason_text":false}
```

**Comment by zheileman** [comment]
Now implemented.
