### ISSUE TITLE
SSL Certificate Expired on API Sandbox

### ISSUE THREAD

**Issue by adamlonsdale** [ministryofjustice/Claim-for-Crown-Court-Defence#1996]
Hi, Developer here.
 
Trying to integrate to the CCD HTTP Upload and when we came to work on Monday the https://api-sandbox-adp.dsd.io/ was down due to an expired certificate. Any way this can be renewed?

**Comment by colinbruce** [comment]
Will do.  Sorry, the root certificate expired so we've been fighting a lot of these fires!

**Comment by colinbruce** [comment]
@adamlonsdale closing ticket.  New SSL cert created and the url is working again
