### ISSUE TITLE
Slack notifier should split on \n

### ISSUE THREAD

**Issue by colinbruce** [ministryofjustice/Claim-for-Crown-Court-Defence#2148]
CCR returns `{ errors: { 'error a\nerror b'} }`

The handler expected `errors: ['error a', 'error b']`

It should handle the correct type and split and join on `\n` instead of using `each` and `join(' ')`

**Comment by colinbruce** [comment]
According to the [Slack API documentation](https://api.slack.com/docs/message-formatting#multiline_messages)
```Multiline Messages
You can post multiline messages through Slack's APIs. 
Insert a newline by including the characters \n in your text. For example:

{
    "text": "This is a line of text.\nAnd this is another one."
}
```
Yet in the notify channel we are receiving
```The supplier account code: '8A222Z' is INVALID!\nThe supplier account code: '8A222Z' is INVALID!```

**Comment by jsugarman** [comment]
Closing as not actioned
