### ISSUE TITLE
Upgrade of paperclip gem

### ISSUE THREAD

**Issue by lostie** [ministryofjustice/Claim-for-Crown-Court-Defence#2342]
✏️ Paperclip version 6 requires `aws-sdk-s3` instead of the current `aws-sdk`, so that gem needs to be set as well.

https://github.com/thoughtbot/paperclip#understanding-storage

**Comment by colinbruce** [comment]
Rails 5.2 introduces active storage http://edgeguides.rubyonrails.org/active_storage_overview.html 

Migration walkthroughs exist : 
https://gorails.com/episodes/migrate-from-paperclip-to-rails-active-storage
Paperclip developers are advocating migration:
https://github.com/thoughtbot/paperclip/pull/2568
and have their own migration guide (WIP)
https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md

**Comment by jsugarman** [comment]
closing as have migrated to activestorage now
