### ISSUE TITLE
JS Rubocopesq

### ISSUE THREAD

**Issue by lostie** [ministryofjustice/Claim-for-Crown-Court-Defence#2416]
I've noticed that we already have https://eslint.org/ [setup](https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/.eslintrc) in this project but we **don't seem to be using it** 😢 .

These tools should be seen as a way to keep the code clean, following the good practices and conventions of the community around it and also as a way to avoid pointless async discussions and comments in PR regarding style and formatting.

I strongly suggest we gradually start to address some of the existent issues and get to a point where we can actually start enforcing this to be active as part of the CI process, the same way Rubocop already is.

Here's the current output for eslint as an example:
[eslint.log](https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/files/2140751/eslint.log)

**Comment by jsugarman** [comment]
@naseberry has this issue been superseded through our use of `yarn run validate:scss` and `yarn run validate:js` and do we still want need/want to have the [eslint](https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/.eslintrc) file in the repo

**Comment by naseberry** [comment]
@jsugarman Yes, this has been superseded by standardJS and Stylelint, however, remnants of the of its configuration remains.

I will create a PR that removes them, then we can close this issue.
