### ISSUE TITLE
Delete S3 files for old reports

### ISSUE THREAD

**Issue by lostie** [ministryofjustice/Claim-for-Crown-Court-Defence#2443]
As part of the existent process to delete old records: https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/51e9880c1afaf632cb37750f2787926a897d91d1/app/models/stats/stats_report.rb#L38-L41

ensure the associated S3 files (if they exists are also removed).

**Comment by jsugarman** [comment]
@jrmhaig does the activestorage migration deal with this issue

**Comment by mpw5** [comment]
Reviewing old issues: `ActiveStorage` handles purging of attachments for deleted reports: ```before_destroy -> { document.purge }```.

Tested in `dev`:

`Stats::StatsReport.last.id` = 1156
`Stats::StatsReport.last.document.id` = 285
`Stats::StatsReport.clean_up("submitted_claims")`
`Stats::StatsReport.find(1156)` = Couldn't find Stats::StatsReport with 'id'=1156
`ActiveStorage::Attachment.find(285)` =  "Couldn't find ActiveStorage::Attachment with 'id'=285"
