### ISSUE TITLE
Demo data seeding not currently working

### ISSUE THREAD

**Issue by lostie** [ministryofjustice/Claim-for-Crown-Court-Defence#2448]
Came to our attention when attempting to setup one of our local environments with demo data that the task is currently failing (likely since the changes to split the claim submission pages and its associated validations). 😰 

https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/9d4ce8e646e4b744b9ead01fe344e3828dcc67d3/lib/tasks/claims.rake#L54

Needs to be looked into, by trying to run them on top of a pristine environment.

**Comment by jsugarman** [comment]
demo data was updated inline with latest validations...closing
