### ISSUE TITLE
Brakeman HAML dependency

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/Claim-for-Crown-Court-Defence#2452]
#### What 
Brakeman errors when run locally via rake task

This can be fixed by updating haml dependencies but should be changed so it 
does not use a rake task in any event. See this [brakeman issue](https://github.com/presidentbeef/brakeman/issues/1044)

**Comment by colinbruce** [comment]
@jsugarman did your PR #2037 fix this?

**Comment by jsugarman** [comment]
Yep @colinbruce
