### ISSUE TITLE
Suggestion / request - use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [ministryofjustice/Claim-for-Crown-Court-Defence#2510]
I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/Claim-for-Crown-Court-Defence/pulls). I've just ported the `nokogiri` one across (#2509) so you can see it in action.

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having open source repos using Dependabot helps boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations (including [alphagov](https://github.com/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+org%3Aalphagov)), and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by jsugarman** [comment]
👍 using this in earnest now
