### ISSUE TITLE
Cucumber reseeding

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/Claim-for-Crown-Court-Defence#2555]
The cuke before hook in [features/support/hooks.rb](https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/features/support/hooks.rb)
```
Before do
  unless ($seed_done ||= false)

    ActiveRecord::Base.connection.reset_pk_sequence!('offences')
    load "#{Rails.root}/db/seeds/courts.rb"
    load "#{Rails.root}/db/seeds/offence_classes.rb"
    load "#{Rails.root}/db/seeds/offences.rb"
    load "#{Rails.root}/db/seeds/scheme_10.rb"
    load "#{Rails.root}/db/seeds/scheme_11.rb"
    load "#{Rails.root}/db/seeds/case_types.rb"
    load "#{Rails.root}/db/seeds/fee_types.rb"
    load "#{Rails.root}/db/seeds/certification_types.rb"
    load "#{Rails.root}/db/seeds/disbursement_types.rb"
    load "#{Rails.root}/db/seeds/expense_types.rb"
    load "#{Rails.root}/db/seeds/vat_rates.rb"
    load "#{Rails.root}/db/seeds/establishments.rb"

    $seed_done = true
  end
end
```
might just work if the code was replaced with 

```
Rake::Task['db:reseed'].invoke
```

and would have the added benefit of testing the task itself

**Comment by colinbruce** [comment]
@jsugarman I tried swapping out the file load method above and replacing it with 
```ruby
Rails.application.load_tasks
Rake::Task['db:reseed'].invoke
```
This is the time difference between the two methods (in seconds)

Run | Files | Rake
-- | -- | --
1 | 39 | 47
2 | 40 | 49
3 | 40 | 46
4 | 40 | 50
5 | 40 | 47
Average | 39.8 | 47.8
Median | 40 | 47

Therefore, I propose leaving the current method as-is... although attempts to speed it it may help long term!

**Comment by jsugarman** [comment]
@colinbruce 👍  - I imagine the performance difference is caused by a database clear and migrate, as well as additional seeds in the rake task (`case_worker`, `super_admins` and `locations`). happy to leave as some of these are redundant unless we actually make use of them in the features 🤔

**Comment by jsugarman** [comment]
closing as not intending to implement
