### ISSUE TITLE
Consolidate API shared examples further

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/Claim-for-Crown-Court-Defence#2661]
The shared specs below could be combined:

RSpec.shared_examples "invalid API key validate endpoint"
RSpec.shared_examples "invalid API key create endpoint"

**Comment by jsugarman** [comment]
@colinbruce Have created an issue for this, from your PR comment

**Comment by mpw5** [comment]
Fixed by https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/pull/4835
