### ISSUE TITLE
Easier SitePrism maintenance / setup

### ISSUE THREAD

**Issue by luke-hill** [ministryofjustice/Claim-for-Crown-Court-Defence#2829]
You can replace a lot of these (https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/features/support/hooks.rb#L6-L27) with a simpler app class

See: https://github.com/natritmeyer/site_prism#epilogue

Regards, Luke Hill - site_prism maintainer

**Comment by jsugarman** [comment]
nice! thanks @luke-hill

**Comment by luke-hill** [comment]
No probs, was just checking on some of the main users of the gem and finding out what I can do as we've got some chunky new features coming in before I start working on a v4 cut.
